[pytest]
pythonpath = .
filterwarnings =
    ignore:datetime.datetime.utcfromtimestamp\(\) is deprecated:DeprecationWarning:dateutil.tz.tz
    ignore:pkg_resources is deprecated as an API:DeprecationWarning:docxcompose.properties
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning:openpyxl.packaging.core
    ignore:datetime.datetime.utcnow\(\) is deprecated:DeprecationWarning:openpyxl.writer.excel
